# importing **torch**

In [69]:
import torch
torch.__version__

'2.1.0+cu121'

In [70]:
loki_list =[1,2,3,4,5]

loki_tensor = torch.tensor(loki_list, dtype =torch.float32)
loki_list=[55]
loki_tensor, loki_list

(tensor([1., 2., 3., 4., 5.]), [55])

# Scalars

In [71]:
scalar = torch.tensor(2)
scalar, scalar.ndim , scalar.shape

(tensor(2), 0, torch.Size([]))

Trnafer learning : one odel learns pattern images of dogs , this training/learning can be passed to other models just like in heritance

In [72]:
vector = torch.tensor([1,2,3], dtype=torch.int64)
vector , vector.ndim  , vector.shape


(tensor([1, 2, 3]), 1, torch.Size([3]))

In [73]:
matrix = torch.tensor([[1,2,3], [4,5,6]])
matrix , matrix.shape , matrix.ndim

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]),
 2)

In [74]:
TENSORp = torch.tensor([ [[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

TENSORp.shape, TENSORp.ndim

(torch.Size([2, 2, 3]), 3)

## Random tensors

In [75]:
randomtensor = torch.rand(2,2,2)
randomtensor
#shappe need to give rand function

tensor([[[0.2591, 0.6633],
         [0.9679, 0.2049]],

        [[0.8966, 0.2362],
         [0.6072, 0.6354]]])

In [76]:
zeros = torch.zeros(size=(3,3), dtype=torch.int8)
zeros

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [77]:
size_tensor = torch.arange(start=0, end=99, step =20)
size_tensor

tensor([ 0, 20, 40, 60, 80])

In [78]:
ten_zeros = torch.zeros_like(input=size_tensor)
ten_zeros
#like will make  tensor of same shape

tensor([0, 0, 0, 0, 0])

In [79]:
float_16_tensor = torch.rand(size=(2,2,2), device="cpu")
float_16_tensor
#default is cpu

tensor([[[0.4196, 0.8063],
         [0.7045, 0.2521]],

        [[0.3269, 0.2070],
         [0.9851, 0.9621]]])

In [80]:
#errors -> multplication of different dtype can be done this is wrong , shape ,  tensors on different device
float_64_tensor =float_16_tensor.type(torch.int32)
float_64_tensor

tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]], dtype=torch.int32)

In [81]:
#random tensors, tensors should be on same devices
rand_t = torch.rand(size=(2,2,2))
rand_t.device , float_16_tensor.device
rand_t*float_16_tensor

tensor([[[0.2828, 0.3047],
         [0.1555, 0.0636]],

        [[0.0796, 0.1965],
         [0.9005, 0.1784]]])

In [82]:
rand_t +3
#element wise operaations with siymbol and scalar vale

tensor([[[3.6740, 3.3779],
         [3.2207, 3.2523]],

        [[3.2436, 3.9490],
         [3.9141, 3.1854]]])

In [83]:
#matrix multiplication -> dot product, in cuda data type should be float 32 for mtrix multplication
tensor1 = torch.tensor([2,3,4] , device='cpu' , dtype= torch.float32)
tensor1*tensor1 #element wise multiplication
%time
torch.matmul(tensor1 , tensor1)
tensor1.device

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 31.5 µs


device(type='cpu')

In [84]:
tensor2=torch.tensor([[11,2,3]]
                     )
tensor2.T

tensor([[11],
        [ 2],
        [ 3]])

In [85]:
torch.mean(tensor2.type(torch.float32))
#for mean requires data type should be in float 32

tensor(5.3333)

In [86]:
tensor2.argmin()

tensor(1)

In [87]:
#view
#reshape
#stacking hstack , vstack
#squeeze , unsqueeze
#permute

In [88]:
tensor3 = torch.rand(size=(2,3,4))
tensor3
tensor4= tensor3.reshape(8,3)
tensor4 , tensor3

(tensor([[0.6617, 0.1129, 0.8013],
         [0.0583, 0.1154, 0.0770],
         [0.1141, 0.4853, 0.1851],
         [0.6878, 0.1340, 0.5946],
         [0.8820, 0.4827, 0.1136],
         [0.5505, 0.7773, 0.8651],
         [0.2916, 0.4657, 0.1939],
         [0.5519, 0.4536, 0.6531]]),
 tensor([[[0.6617, 0.1129, 0.8013, 0.0583],
          [0.1154, 0.0770, 0.1141, 0.4853],
          [0.1851, 0.6878, 0.1340, 0.5946]],
 
         [[0.8820, 0.4827, 0.1136, 0.5505],
          [0.7773, 0.8651, 0.2916, 0.4657],
          [0.1939, 0.5519, 0.4536, 0.6531]]]))

In [89]:
#squeeze, remove all single dimensions  from shape u can see diffrenece
tensor4 = torch.rand(1,3,4,2,1,5)
tensor5= torch.squeeze(tensor4)
tensor4.shape , tensor5.shape
tensor6=torch.unsqueeze(tensor5 , dim =-5)
tensor6.shape

torch.Size([1, 3, 4, 2, 5])

In [90]:
#permute with specified index === reshape with dimensions
x = torch.rand(3,224,224)
y = torch.permute(x, (2,0,1))
y.shape

torch.Size([224, 3, 224])

In [97]:
#numpy is scienctific  computing library
import numpy as np
npA = np.array([1,2,3])
#how to get numpy data tpo torch ??

npA_tensor = torch.from_numpy(npA).type(torch.float32)
npA_tensor

tensor([1., 2., 3.])

In [100]:
npA[0]=npA[0]+1
npA , npA_tensor
#tensor not changed

(array([4, 2, 3]), tensor([1., 2., 3.]))

In [107]:
#tensor to numpy, here memory sharing happening please take care
tensor = torch.ones(2,2,3).type(torch.int32)
numpy_tensor = tensor.numpy()
numpy_tensor
numpy_tensor[0]=numpy_tensor[0]*10
tensor , numpy_tensor

(tensor([[[10, 10, 10],
          [10, 10, 10]],
 
         [[ 1,  1,  1],
          [ 1,  1,  1]]], dtype=torch.int32),
 array([[[10, 10, 10],
         [10, 10, 10]],
 
        [[ 1,  1,  1],
         [ 1,  1,  1]]], dtype=int32))

In [114]:
torch.rand(3,3,3)
#random number duffere when you run again
#we need reproducibility , of same data when ypu share this notebook to others
RANDOM_SEED =42
torch.manual_seed(RANDOM_SEED)
TENSORC = torch.rand(3,3)
torch.manual_seed(RANDOM_SEED)
TENSORD = torch.rand(3,3)
TENSORC,TENSORD

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]))

In [118]:
#running pytorch objects on GPU'S
#google  colab
#cloud computing - GCP ,AWS,AZURE , rent these
torch.cuda.is_available()

False

In [119]:
device='cuda' if torch.cuda.is_available() else 'cpu'
device
#gpu make computation faster

'cpu'